# Generated by Django 3.0.5 on 2020-06-27 05:32

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketresponse',
            name='result',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
