# Generated by Django 3.0.8 on 2020-07-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200626_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketresponse',
            name='email',
        ),
        migrations.AddField(
            model_name='preparedpdf',
            name='key_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='ticketresponse',
            name='key_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='ticketresponse',
            name='result',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
