# Generated by Django 3.0.8 on 2020-07-06 21:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200703_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketresponse',
            name='file_guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
