# Generated by Django 3.0.8 on 2020-08-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ticketresponse_file_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketresponse',
            name='email_message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
