# Generated by Django 3.0.8 on 2020-08-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ticketresponse_email_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketresponse',
            name='detachment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticketresponse',
            name='enforcement_officer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
