---
kind: Template
apiVersion: v1
metadata:
  annotations:
    description: Build template for a django server.
    tags: django
    iconClass: icon-python
  name: "${NAME}-build-template"
objects:

  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "${NAME}"

  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "${NAME}"
      labels:
        app: "${NAME}"
    spec:
      source:
        type: Git
        git:
          uri: "${GIT_REPO_URL}"
          ref: "${GIT_REF}"
        contextDir: "${SOURCE_CONTEXT_DIR}"
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: "${KIND_OF_IMAGE}"
            name: "${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}"
          env:
          - name: PIP_INDEX_URL
            value: "${PIP_INDEX_URL}"
          - name: UPGRADE_PIP_TO_LATEST
            value: "${UPGRADE_PIP_TO_LATEST}"
          - name: PIP_NO_CACHE_DIR
            value: "${PIP_NO_CACHE_DIR}"
      output:
        to:
          kind: ImageStreamTag
          name: "${NAME}:${OUTPUT_IMAGE_TAG}"
      resources:
        requests:
          cpu: "${CPU_REQUEST}"
          memory: "${MEMORY_REQUEST}"
        limits:
          cpu: "${CPU_LIMIT}"
          memory: "${MEMORY_LIMIT}"
      triggers:
        - type: ImageChange
        - type: ConfigChange

parameters:
  - name: NAME
    displayName: Name
    description:
      The name assigned to all of the objects defined in this template.  You
      should keep this as default unless your know what your doing.
    required: true
    value: django
  - name: ENV_NAME
    displayName: Environment Name
    description: Environment name.  For the build environment this will typically be 'tools'
    required: true
    value: tools
  - name: GIT_REPO_URL
    displayName: Git Repo URL
    description:
      The URL to your GIT repo, don't use the this default unless your just
      experimenting.
    required: true
    value: https://github.com/bcgov/violation-dispute-form.git
  - name: GIT_REF
    displayName: Git Reference
    description: The git reference or branch.
    required: true
    value: master
  - name: SOURCE_CONTEXT_DIR
    displayName: Source Context Directory
    description: The source context directory.
    required: true
    value: virtual-hearing-form-api
  - name: KIND_OF_IMAGE
    displayName: Kind of the Source Image
    required: true
    description: The kind of the source image.
    value: DockerImage
  - name: SOURCE_IMAGE_NAME
    displayName: Source Image Name
    required: true
    description: The name of the source image.
    value: registry.fedoraproject.org/f32/python3
  - name: SOURCE_IMAGE_TAG
    displayName: Source Image Tag
    required: true
    description: The tag of the source image.
    value: "latest"
  - name: OUTPUT_IMAGE_TAG
    displayName: Output Image Tag
    description: The tag given to the built image.
    required: true
    value: latest
  - name: PIP_INDEX_URL
    displayName: Custom PyPi Index URL
    description: The custom PyPi index URL
    value: ''
  - name: UPGRADE_PIP_TO_LATEST
    displayName: Upgrade Pip To Latest
    description: Upgrade Pip To Latest
    value: 'true'
  - name: PIP_NO_CACHE_DIR
    displayName: Pip No Cache Dir
    description: Pip No Cache Dir
    value: ''
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: '1'
  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 1Gi
  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: 250m
  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 250m