---
kind: Template
apiVersion: v1
metadata:
  name: "${NAME}-deployment-template"
  annotations:
    description:
      Deployment template for a django server connected to a PostGreSQL
      database.
    tags: django
    iconClass: icon-python
objects:
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_NAME}
        env: ${TAG_NAME}
    spec:
      description: |
        Allow the front-end application to access the API.
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  role: web
                  app: ${APP_NAME}
                  env: ${TAG_NAME}
              namespaceSelector:
                matchLabels:
                  name: ${NAMESPACE_NAME}
                  environment: ${TAG_NAME}
          ports:
            - protocol: TCP
              port: 8080
      podSelector:
        matchLabels:
          role: ${ROLE}
          app: ${APP_NAME}
          env: ${TAG_NAME}

  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_NAME}
        role: ${ROLE}
        env: ${TAG_NAME}
      annotations:
        description: Exposes and load balances the application pods
        service.alpha.openshift.io/dependencies: '[{"name": "${DATABASE_SERVICE_NAME}", "kind": "Service"}]'
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          targetPort: 8080
      selector:
        name: ${NAME}

  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_NAME}
        role: ${ROLE}
        env: ${TAG_NAME}
    stringData:
      recaptcha-site-key: ${RECAPTCHA_SITE_KEY}
      recaptcha-secret-key: ${RECAPTCHA_SECRET_KEY}
      ches-auth-url: ${CHES_AUTH_URL}
      ches-email-url: ${CHES_EMAIL_URL}
      email-service-client-id: ${EMAIL_SERVICE_CLIENT_ID}
      email-service-client-secret: ${EMAIL_SERVICE_CLIENT_SECRET}
      sender-email: ${SENDER_EMAIL}
      sender-name: ${SENDER_NAME}
      feedback-email: ${FEEDBACK_TARGET_EMAIL}
      encryption-key: ${DATA_SECURITY_KEY}
      oidc-rp-provider-endpoint: ${OIDC_RP_PROVIDER_ENDPOINT}
      oidc-rp-client-secret: ${OIDC_RP_CLIENT_SECRET}
    type: Opaque

  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_NAME}
        role: ${ROLE}
        env: ${TAG_NAME}
      annotations:
        description: Defines how to deploy the application server
    spec:
      strategy:
        type: Rolling
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}
            from:
              kind: ImageStreamTag
              namespace: "${IMAGE_NAMESPACE}"
              name: "${NAME}:${TAG_NAME}"
        - type: ConfigChange
      replicas: 1
      selector:
        name: ${NAME}
      template:
        metadata:
          name: ${NAME}
          labels:
            name: ${NAME}
            app: ${APP_NAME}
            role: ${ROLE}
            env: ${TAG_NAME}
        spec:
          containers:
            - name: ${NAME}
              image: " "
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                initialDelaySeconds: 3
                timeoutSeconds: 30
                httpGet:
                  path: "/health/"
                  port: 8080
              livenessProbe:
                initialDelaySeconds: 120
                timeoutSeconds: 30
                httpGet:
                  path: "/health/"
                  port: 8080
              env:
                - name: DATABASE_SERVICE_NAME
                  value: "${DATABASE_SERVICE_NAME}"
                - name: DATABASE_ENGINE
                  value: "${DATABASE_ENGINE}"
                - name: DATABASE_NAME
                  value: "${DATABASE_NAME}"
                - name: DATABASE_USER
                  valueFrom:
                    secretKeyRef:
                      name: "${DATABASE_DEPLOYMENT_NAME}"
                      key: database-user
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: "${DATABASE_DEPLOYMENT_NAME}"
                      key: database-password
                - name: APP_CONFIG
                  value: "${APP_CONFIG}"
                - name: DJANGO_SECRET_KEY
                  value: "${DJANGO_SECRET_KEY}"
                - name: DJANGO_DEBUG
                  value: "${DJANGO_DEBUG}"
                - name: PDF_SERVICE_URL
                  value: ${PDF_SERVICE_URL}

                - name: RECAPTCHA_SITE_KEY
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}
                      key: recaptcha-site-key
                - name: RECAPTCHA_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}
                      key: recaptcha-secret-key

                - name: CHES_AUTH_URL
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}
                      key: ches-auth-url
                - name: CHES_EMAIL_URL
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}
                      key: ches-email-url
                - name: EMAIL_SERVICE_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}
                      key: email-service-client-id
                - name: EMAIL_SERVICE_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}
                      key: email-service-client-secret
                - name: FEEDBACK_TARGET_EMAIL
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}
                      key: feedback-email
                - name: SENDER_EMAIL
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}
                      key: sender-email
                - name: SENDER_NAME
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}
                      key: sender-name

                - name: DATA_SECURITY_KEY
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}
                      key: encryption-key

                - name: OIDC_RP_PROVIDER_ENDPOINT
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}
                      key: oidc-rp-provider-endpoint
                - name: OIDC_RP_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}
                      key: oidc-rp-client-secret
                - name: OIDC_RP_KC_IDP_HINT
                  value: ${OIDC_RP_KC_IDP_HINT}

              resources:
                requests:
                  cpu: "${CPU_REQUEST}"
                  memory: "${MEMORY_REQUEST}"
                limits:
                  cpu: "${CPU_LIMIT}"
                  memory: "${MEMORY_LIMIT}"

  - kind: HorizontalPodAutoscaler
    apiVersion: autoscaling/v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_NAME}
        role: ${ROLE}
        env: ${TAG_NAME}
    spec:
      scaleTargetRef:
        kind: DeploymentConfig
        name: ${NAME}
      minReplicas: ${{MIN_REPLICAS}}
      maxReplicas: ${{MAX_REPLICAS}}

parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the OpenShift resources associated to the server instance.
    required: true
    value: django

  - name: APP_NAME
    displayName: App Name
    description: App Name
    required: true
    value: virtual-hearing-form
  - name: ROLE
    displayName: Role
    description: Role
    required: true
    value: api

  - name: NAMESPACE_NAME
    displayName: Namespace Name
    description: The base namespace name for the project.
    required: true
    value: "069465"

  - name: IMAGE_NAMESPACE
    displayName: Image Namespace
    required: true
    description: The namespace of the OpenShift project containing the imagestream for the application.
    value: 069465-tools
  - name: DATABASE_SERVICE_NAME
    displayName: Database Service Name
    description: The name of the database server/service.
    required: true
    value: postgresql
  - name: DATABASE_ENGINE
    displayName: Database Engine
    required: true
    description: "Database engine: postgresql, mysql, or sqlite (default)."
    value: postgresql
  - name: DATABASE_NAME
    displayName: Database Name
    required: true
    description: Name of the deployed database (see environment variables in deployed database).
    value: App_Database
  - name: APP_CONFIG
    displayName: Application Configuration File Path
    description: Relative path to Gunicorn configuration file (optional).
  - name: DJANGO_SECRET_KEY
    displayName: Django Secret Key
    description: Set this to a long random string.
    generate: expression
    from: "[\\w]{50}"
  - name: DJANGO_DEBUG
    displayName: Django Debug
    description: If Django is in debug mode
    required: true
    value: "False"
  - name: PDF_SERVICE_URL
    displayName: PDF Service URL
    description: Internal URL to the PDF service.
    required: true
    value: "http://weasyprint:5001"
  - name: TAG_NAME
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod
    value: dev
    required: true
  - name: DATABASE_DEPLOYMENT_NAME
    displayName: Database Deployment Name
    description: The name associated to the database deployment resources.  In particular, this is used to wrie up the credentials associated to the database.
    required: true
    value: postgresql

  - name: RECAPTCHA_SITE_KEY
    displayName: reCAPTCHA Site Key
    description: reCAPTCHA Site Key.
    required: false
    value:
  - name: RECAPTCHA_SECRET_KEY
    displayName: reCAPTCHA Secret Key
    description: reCAPTCHA Secret Key.
    required: false
    value:

  - name: CHES_AUTH_URL
    displayName: CHES authentication url
    description: CHES authentication url
    required: true
    value:
  - name: CHES_EMAIL_URL
    displayName: CHES email url
    description: CHES email url
    required: true
    value:
  - name: EMAIL_SERVICE_CLIENT_ID
    displayName: Email Service Client Id
    description: Email Service Client Id
    required: true
    value:
  - name: EMAIL_SERVICE_CLIENT_SECRET
    displayName: Email Service Client Secret
    description: Email Service Client Secret
    required: true
    value:
  - name: FEEDBACK_TARGET_EMAIL
    displayName: Feedback target email address
    description: Feedback target email address
    required: false
    value:
  - name: SENDER_EMAIL
    displayName: Sender email address
    description: Sender email address
    required: true
    value:
  - name: SENDER_NAME
    displayName: Sender name
    description: Sender name
    required: true
    value: Virtual Traffic Hearing Notification

  - name: DATA_SECURITY_KEY
    displayName: Data Security (Encryption) Key
    description: The Encryption Key for the environment.
    generate: expression
    from: "[a-zA-Z0-9]{32}"

  - name: OIDC_RP_PROVIDER_ENDPOINT
    displayName: OIDC RP Provider Endpoint
    description: OIDC RP Provider Endpoint.
    required: false
    value:
  - name: OIDC_RP_CLIENT_SECRET
    displayName: OIDC RP Client Secret
    description: OIDC RP Client Secret
    required: false
    value:
  - name: OIDC_RP_KC_IDP_HINT
    displayName: OIDC RP KeyCloak IDP Hint
    description: OIDC RP KeyCloak IDP Hint
    required: false
    value: idir

  # ===============================================================================
  - name: MIN_REPLICAS
    displayName: Minimum Replicas
    description: The minimum number of pods to have running.
    required: true
    value: "3"
  - name: MAX_REPLICAS
    displayName: Maximum Replicas
    description: The maximum number of pods to have running.
    required: true
    value: "6"
  # ===============================================================================

  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: 10m
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: 500m
  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 10Mi
  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 1Gi
